### PR TITLE
Added hotkey to resolve #1

### LINKED ISSUE #1: Keyboard Shortcut?
Hi,
i wanted to say thank you!
I have lots of passphrases which i'm using in very specific environments (like VM in a browser tab in another VM via RDP) and the only way is typing the damn 32 complicated chars passphrases each time!
It's working great.

Just one note.. is there anyway we could use a keyboard shortcut and not pointing mouse and click on the target screen? i mean i'm already focused on the target window, so i can use a shortcut just to type the text.

Regards
Mehrdad

### PR DESCRIPTION
**Pull request by randomizer3000**
This should resolve #1 by adding a configurable keyboard hotkey to activate the program (same as if you clicked on the icon) 
Modifiers are set via an enum
        Alt = 1,
        Control = 2,
        Shift = 4,
        Windows = 8,
        NoRepeat = 0x4000

### CODE REVIEW

**Review by f3rrix — COMMENTED** [review]
Cool I'll integrate this!

**Comment by Atario** [comment]
Erm.  No release for this?

**Comment by tms1003** [comment]
How do I set this up?  Do I need to wait for an official release?

**Comment by randomizer3000** [comment]
Since this PR has not been merged you would need to checkout either this PR or my fork and compile it yourself

**Comment by f3rrix** [comment]
I have been trying to get to this for so long. And today is the day!

**Review by f3rrix — APPROVED** [review]
Sorry for taking so long :)

**Comment by Atario** [comment]
Thank you @f3rrix !  (Now I kinda wish there was a way to trigger the paste itself by pressing a key, instead of having to switch over to the mouse button…)

**Comment by Atario** [comment]
Will do, and thanks again

**Pull request merged**
